spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/cyber_zero
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: DEBUG
file:
  storage:
    path: "C:/Users/Aziza/Desktop/files" # Ensure this path is correct for your environment